In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import os

In [2]:
titles = []
Description = []
Price = []
Date_Place = []

for file_number in range(2, 72):

    with open(f"/home/sgouros/Desktop/Test/WebScrab3/BazarakiHtml/test{file_number}.html", "r") as reader:
        html_string = reader.read()
        soup = BeautifulSoup(html_string, "html.parser")

    for box in soup.find_all(class_="list-announcement-block"):
        titles.append(box.find_all(class_="announcement-block__title")[0].text.strip())
        Description.append(box.find_all(class_="announcement-block__description")[0].text.strip())
        Price.append(box.find_all(class_="announcement-block-link announcement-block__link")[0].text.strip())
        Date_Place.append(box.find_all(class_="announcement-block__date")[0].text.strip())

In [3]:
table = pd.DataFrame(data={"Car":titles, "Km_Transmission_Gas":Description, "Price":Price, "Date_Place":Date_Place})

In [4]:
table

,Car,Km_Transmission_Gas,Price,Date_Place
0,"Land Rover Defender 2,0L 2020","50000 km, Automatic, Diesel",€89.000,"21.01.2023 08:32,\n Paphos dist..."
1,"Lamborghini Urus 4,0L 2020","15000 km, Automatic, Petrol",€349.000,"21.01.2023 08:32,\n Paphos dist..."
2,"Chevrolet Spark 1,0L 2012","130000 km, Manual, Petrol",€3.500 \n \n \n \n ...,"Yesterday 10:06,\n Limassol distric..."
3,"Nissan Note e-Power 1,2L 2019","32000 km, Automatic, Hybrid Petrol",€15.650,"19.01.2023 15:09,\n Limassol distri..."
4,"Subaru XV 2,0L 2020","13000 km, Automatic, Hybrid Petrol",€29.950,"Today 15:36,\n Limassol district, L..."
...,...,...,...,...
4755,"Ford Focus 1,5L 2018","62000 km, Manual, Diesel",€18.000,"27.12.2022 05:49,\n Lefkosia (Nicos..."
4756,"Suzuki Solio 1,3L 2015","57000 km, Automatic, Petrol",€8.990,"27.12.2022 02:24,\n Larnaca distric..."
4757,"Smart Fortwo 0,9L 2018","48200 km, Automatic, Petrol",€17.999,"27.12.2022 02:11,\n Lefkosia (Nicos..."
4758,"Volkswagen Golf 1,4L 2008","159000 km, Automatic, Petrol",€5.500 \n \n \n ...,"27.12.2022 01:23,\n Lefkosia (Nicos..."
4759,"Honda Jazz 1,3L 2007","154000 km, Manual, Petrol",€4.500,"27.12.2022 00:16,\n Limassol distri..."

In [5]:
table.to_csv("car_prices_bazaraki.csv", index=False)